spring.application.name=demo


spring.ai.google.genai.api-key=AIzaSyCzvtzRDRE9cWC0UywreMK4PQjHhWLM4rA
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.2
spring.ai.google.genai.chat.options.max-tokens=200